### ISSUE TITLE
milestones

### ISSUE THREAD

**Issue by tmjoen** [univers-agency/hjernen#9]
- [ ] project has milestones
  - [ ] end date for each milestone
  - [ ] tasks per milestone
